//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H264CameraUtil.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\log\\cameraParams.xml")]
        public string CAMERA_PARAMS_FILE_NAME {
            get {
                return ((string)(this["CAMERA_PARAMS_FILE_NAME"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\log")]
        public string CAMERA_RECORDER_OUTPUT_FOLDER {
            get {
                return ((string)(this["CAMERA_RECORDER_OUTPUT_FOLDER"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ED_")]
        public string CAMERA_RECORDER_OUTPUT_PREFIX {
            get {
                return ((string)(this["CAMERA_RECORDER_OUTPUT_PREFIX"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mp4")]
        public string CAMERA_RECORDER_OUTPUT_EXT {
            get {
                return ((string)(this["CAMERA_RECORDER_OUTPUT_EXT"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8554")]
        public string CAMERA_STREAMER_PORT {
            get {
                return ((string)(this["CAMERA_STREAMER_PORT"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("stream")]
        public string CAMERA_STREAMER_NAME {
            get {
                return ((string)(this["CAMERA_STREAMER_NAME"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int KEY_LISTENER_DELAY {
            get {
                return ((int)(this["KEY_LISTENER_DELAY"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int RECORDER_OVERLAP_DURATION {
            get {
                return ((int)(this["RECORDER_OVERLAP_DURATION"]));
            }
            set {
                this["RECORDER_OVERLAP_DURATION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RUN_RECORDER_SERVICE {
            get {
                return ((bool)(this["RUN_RECORDER_SERVICE"]));
            }
            set {
                this["RUN_RECORDER_SERVICE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RUN_STREAMER_SERVICE {
            get {
                return ((bool)(this["RUN_STREAMER_SERVICE"]));
            }
            set {
                this["RUN_STREAMER_SERVICE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RUN_VIEWER_SERVICE {
            get {
                return ((bool)(this["RUN_VIEWER_SERVICE"]));
            }
            set {
                this["RUN_VIEWER_SERVICE"] = value;
            }
        }
    }
}
